### PR TITLE
moving from godep to trash

### PR DESCRIPTION
**Pull request by rheinwein**
**Problem**
Godep is a great tool for managing dependencies, but counts on the fact that your `$GOPATH` is the source of truth for which versions of packages need to be used. Godep functions primarily by copying things back and forth between your `$GOPATH` and the project `vendor` directory. This is fine when all of the projects you work on keep their dependency trees healthy and up-to-date. It begins to fall apart when you have multiple open-source projects with varying levels of dependency cleanliness. Godep also has some design flaws that are extremely irritating -- like leaving packages in your `$GOPATH` in detached `HEAD` state during a `godep restore`. Because of these issues, different golang package managers have begun popping up.

**Options**
Here's a long list of dependency managers: https://github.com/golang/go/wiki/PackageManagementTools
Additionally, I've really come to love the way that Docker handles deps in their projects. There's a script that basically `rm -rf`s `vendor`, then repopulates it based on SHA/tags in a dependency list. It's hacky, but it works.

**Proposed solution**
We should aim to find a solution somewhere in the middle between `glide` and the `hack/vendor.sh` solution that Docker uses. Specifically, this solution should:
1. Allow us to manually update a dependency manifest with SHAs or tags of the packages we want
2. Install the dependencies directly in the vendor path, and not copy them from our `$GOPATH`
3. Reduce the size of the `vendor` folder by removing extraneous files (like test files) unneeded to satisfy the package dependency.
4. It should be actively maintained

I took some time to look into each of the viable options, and I think the best solution for our specific problems is [trash](https://github.com/rancher/trash), a project from Rancher. It feels a lot like the Docker scripty way of doing things, but has a more structured manifest and some extra features. It also removes test files, _testdata, and licenses from the `vendor` directory to keep the total project size down. Awesome!

Here's an example of what it looks like to use `trash` in a project. If we all agree, we can implement it here first, and then gradually move to use `trash` on other golang components of our system.

### CODE REVIEW

**Comment by bfosberry** [comment]
Currently heroku uses godeps to determine what go version to run, how will this affect our heroku deploys?

**Comment by bfosberry** [comment]
That question applies less to this project, totally up for this change here as long as we implement a system wide change and as long as trash works across our internal deps

**Comment by beanieboi** [comment]
they use a couple of different checks: https://github.com/heroku/heroku-buildpack-go/blob/master/bin/detect

**Comment by rheinwein** [comment]
My goal is definitely to use a different dependency manager for all of our go projects and have common tooling across the codeship org. I think we've solved the versioning problem with Heroku but will verify it before going forward, thanks @beanieboi @bfosberry!

**Pull request merged**
